[package]
edition = "2021"
name = "aos_data_proxy"
version = "0.5.0-beta.3"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
anyhow = "1.0"
aruna-rust-api = "0.5.0-beta.3"
async-channel = "1.6"
async-stream = "0.3"
async-trait = "0.1"
aws-config = "0"
aws-sdk-s3 = "0"
aws-smithy-http = "0.45"
base64 = "0.13"
bytes = "1.1"
chrono = "0.4"
dotenv = "0.15.0"
env_logger = "0"
futures = "0.3"
futures-channel = "0.3"
futures-core = "0.3"
futures-util = "0.3"
hmac = "0.12"
http = "0"
hyper = {version = "0.14", features = ["full"]}
log = "0.4"
rand = "0.8"
reqwest = "0"
serde = {version = "1.0", features = ["derive"]}
sha2 = {version = "0.10", features = ["std", "asm", "sha2-asm"]}
tokio = {version = "1", features = ["full"]}
tonic = "0.8"
url = "2.2"
uuid = {version = "1", features = ["v4", "fast-rng"]}
[build-dependencies]
tonic-build = "0.8"
