[package]
edition = "2021"
name = "aos_data_proxy"
version = "1.0.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
aruna-file = "0.2.0-rc.14"
aruna-rust-api = "2.0.0-alpha.8"
async-channel = "1.9.0"
async-stream = "0.3.5"
async-trait = "0.1.73"
axum = "0.6.20"
aws-config = "0.56.0"
aws-sdk-s3 = "0.29.0"
aws-smithy-http = "0.56.0"
base64 = "0.21.2"
byteorder = "1.4.3"
bytes = "1.4.0"
chrono = "0.4.26"
dotenvy = "0.15.7"
env_logger = "0.10.0"
futures = "0.3.28"
futures-channel = "0.3.28"
futures-core = "0.3.28"
futures-util = "0.3.28"
hex = "0.4"
hmac = "0.12.1"
http = "0.2.9"
hyper = {version = "0.14.27", features = ["full"]}
log = "0.4.20"
md-5 = "0.10.5"
rand = "0.8.5"
reqwest = "0.11.18"
s3s = "0.7.0"
serde = {version = "1.0.185", features = ["derive"]}
sha2 = {version = "0.10.7", features = ["std", "asm", "sha2-asm"]}
tokio = {version = "1.32.0", features = ["full"]}
tokio-stream = "0.1.14"
tower = { version = "0.4.13", features = ["retry"] }
tonic = {version = "0.9.2", features = ["tls"]}
tracing = "0.1.37"
tracing-error = "0.2.0"
tracing-subscriber = {version = "0.3.17", optional = true, features = ["env-filter", "time"]}
url = "2.4.0"
zstd = "0.12.4"
diesel-ulid = "0.3.0"
bincode = "1.3.3"
tokio-postgres = { version = "0.7.9", features = ["with-uuid-1", "with-serde_json-1", "with-chrono-0_4"] }
postgres-types = { version = "0.2.6", features = ["derive"] }
postgres_array = "0.11.1"
deadpool-postgres = "0.10.5"
postgres-from-row = "=0.5.2"
dashmap = "5.5.0"
ahash = "0.8.3"
jsonwebtoken = {version = "8.3.0", features = ["use_pem"]}
