[package]
edition = "2021"
name = "aos_data_proxy"
version = "1.0.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
aruna-file = "0.2.0-rc.14"
aruna-rust-api = "1.1.0-rc.6"
async-channel = "1.8.0"
async-stream = "0.3.5"
async-trait = "0.1.68"
axum = "0.6.18"
aws-config = "0.55.3"
aws-sdk-s3 = "0.26.0"
aws-smithy-http = "0.55.3"
base64 = "0.21.2"
byteorder = "1.4.3"
bytes = "1.4.0"
chrono = "0.4.26"
dotenvy = "0.15.7"
env_logger = "0.10.0"
futures = "0.3.28"
futures-channel = "0.3.28"
futures-core = "0.3.28"
futures-util = "0.3.28"
hex = "0.4"
hmac = "0.12.1"
http = "0.2.9"
hyper = {version = "0.14.27", features = ["full"]}
log = "0.4.19"
md-5 = "0.10.5"
rand = "0.8.5"
reqwest = "0.11.18"
rusty_ulid = "2.0.0"
s3s = "0.4.0"
serde = {version = "1.0.164", features = ["derive"]}
sha2 = {version = "0.10.7", features = ["std", "asm", "sha2-asm"]}
tokio = {version = "1.29.1", features = ["full"]}
tokio-stream = "0.1.14"
tower = { version = "0.4.13", features = ["retry"] }
tonic = "0.9.2"
tracing = "0.1.37"
tracing-error = "0.2.0"
tracing-subscriber = {version = "0.3.17", optional = true, features = ["env-filter", "time"]}
url = "2.4.0"
zstd = "0.12.3+zstd.1.5.2"

[build-dependencies]
tonic-build = "0.9.2"
